Added comment in build.gradle and developing.md for heap size
OpenLiberty/liberty-tools-intellij pull request #1200
Opened 2024-12-18 14:34 UTC by staicy123

2024-12-19 03:44 UTC, vaisakhkannan requested changes

2024-12-19 03:44 UTC, vaisakhkannan commented on DEVELOPING.md
> +2. Increase the `memoryMaximumSize` in the `JavaCompile` task. For example: tasks.withType(JavaCompile) { options.forkOptions.memoryMaximumSize = "4g" // Increase to 4GB or more if needed }
@staicy123 , Can you highlight this part `tasks.withType(JavaCompile) { options.forkOptions.memoryMaximumSize = "4g"` similar to what you did for `memoryMaximumSize` and `JavaCompile`

2024-12-19 11:11 UTC, vaisakhkannan approved these changes
Looks good

2024-12-23 16:22 UTC, TrevCraw approved these changes

2025-01-02 16:50 UTC, mrglavas approved these changes
Looks good. Thanks.

2025-01-04 10:24 UTC, merged