Change the menu option name from "Liberty: View effective POM" to "Liberty: View pom.xml"
OpenLiberty/liberty-tools-intellij pull request #638
Opened 2024-02-02 04:48 UTC by vaisakhkannan

Fixes #615 --> Changed the menu option name from "Liberty: View effective POM" to "Liberty: View pom.xml"

2024-02-02 07:01 UTC, anusreelakshmi934 reviewed
Update the copyrights in modified files.

2024-02-02 12:50 UTC, anusreelakshmi934 approved these changes

2024-02-02 23:51 UTC, TrevCraw requested changes

2024-02-02 23:51 UTC, TrevCraw commented on src/main/resources/messages/LibertyBundles.properties
> +action.io.openliberty.tools.intellij.actions.ViewEffectivePom.text=Liberty: View pom.xml
We should also update the name of the action here and throughout the rest of the code as well. `ViewPom` or `ViewPomXml` would be good.

2024-02-05 11:56 UTC, anusreelakshmi934 submitted a review, later dismissed

2024-04-29 20:52 UTC, TrevCraw requested changes
The following lines also need to be updated:
- LibertyBundles.properties - https://github.com/OpenLiberty/liberty-tools-intellij/blob/main/src/main/resources/messages/LibertyBundles.properties#L93-L94
- ViewPomXml.java - https://github.com/OpenLiberty/liberty-tools-intellij/blob/main/src/main/java/io/openliberty/tools/intellij/actions/ViewEffectivePom.java#L30

2024-04-30 09:18 UTC, anusreelakshmi934 approved these changes
Looks good to me.

2024-04-30 18:08 UTC, TrevCraw requested changes

2024-04-30 18:08 UTC, TrevCraw commented on src/main/resources/messages/LibertyBundles.properties
>  # View effective pom action
```suggestion
# View pom.xml action
```

2024-05-07 07:51 UTC, anusreelakshmi934 approved these changes

2024-05-09 18:27 UTC, TrevCraw approved these changes

2024-05-10 04:25 UTC, merged