Documentation for developers to understand continuous build integration
OpenLiberty/liberty-tools-intellij pull request #990
Opened 2024-09-25 12:15 UTC by anusreelakshmi934

Fixes #896

2024-09-26 06:08 UTC, TrevCraw requested changes
Overall, looks good! Made some minor suggestions.

I think we should also include a link to the new continuous integration doc from the DEVELOPING.md page.

2024-09-26 06:08 UTC, TrevCraw commented on docs/user-guide.md
> +When installing the LTI Plugin, the latest version of LSP4IJ from the marketplace will be installed by default.
```suggestion
When installing the Liberty Tools for IntelliJ plugin, the latest version of LSP4IJ from the JetBrains marketplace will be installed by default.
```

2024-09-26 06:08 UTC, TrevCraw commented on docs/user-guide.md
> +If you prefer to use an older version of LSP4IJ (e.g., the specific version that was tested with the LTI release you are using), you can manually downgrade it by installing the desired version as a d
```suggestion
If you prefer to use an older version of LSP4IJ (e.g., the specific version that was tested with the Liberty Tools release you are using), you can manually downgrade it by installing the desired version as a dependency from the JetBrains marketplace. Link to download a specific LSP4IJ version - https://plugins.jetbrains.com/plugin/23257-lsp4ij/versions
```

2024-09-26 06:08 UTC, TrevCraw commented on README.md
> +Users who wish to change the version of LSP4IJ installed along with LTI can refer to this resource [here](docs/user-guide.md#manually-install-specific-release-of-the-lsp4ij-plugin-from-the-marketplac
```suggestion
If you wish to change the version of LSP4IJ installed along with Liberty Tools, you can refer to the documentation [here](docs/user-guide.md#manually-install-specific-release-of-the-lsp4ij-plugin-from-the-marketplace).
```

2024-09-26 06:27 UTC, anusreelakshmi934 commented on docs/LSP4IJ-Integration.md
> +    - [Overview](#overview)
I initially thought only the main subsections need to be mentioned there. will change that.

2024-09-26 06:42 UTC, anusreelakshmi934 commented on docs/LSP4IJ-Integration.md
> +
Ok will change

2024-09-26 06:47 UTC, anusreelakshmi934 commented on docs/LSP4IJ-Integration.md
> +### Jobs
Ok

2024-09-26 09:15 UTC, anusreelakshmi934 commented on docs/LSP4IJ-Integration.md
> +The job **Run Lsp4ij Main** is the build which run against the lsp4ij main branch by checking out lsp4ij main branch. The job **Run PR** run by checking out the merge commit SHAs of each PR listed in
PR details is a job and its output is the list of PRs.

2024-09-26 10:07 UTC, anusreelakshmi934 commented on docs/LSP4IJ-Integration.md
> +The job **Run Lsp4ij Main** is the build which run against the lsp4ij main branch by checking out lsp4ij main branch. The job **Run PR** run by checking out the merge commit SHAs of each PR listed in
@TrevCraw I have modified this section.

2024-09-26 21:43 UTC, TrevCraw requested changes

2024-09-26 21:43 UTC, TrevCraw commented on DEVELOPING.md
> +For details on the Continuous Integration (CI) setup for LSP4IJ integration, refer to the [LSP4IJ Continuous Integration user guide.](docs/LSP4IJ-Continuous-Integration.md)
```suggestion
For details on the Continuous Integration (CI) setup for LSP4IJ integration, refer to the [LSP4IJ Continuous Integration documentation.](docs/LSP4IJ-Continuous-Integration.md) 
```

2024-09-26 21:43 UTC, TrevCraw commented on README.md
> +Liberty Tools for IntelliJ includes LSP4IJ, an external plugin dependency that is automatically installed with LTI. LSP4IJ is a free and open-source Language Server Protocol (LSP) client developed by
```suggestion
Liberty Tools for IntelliJ includes LSP4IJ, an external plugin dependency that is automatically installed with Liberty Tools. LSP4IJ is a free and open-source Language Server Protocol (LSP) client developed by Red Hat, enabling seamless language server integration.
```

2024-09-26 21:43 UTC, TrevCraw commented on docs/LSP4IJ-Integration.md
> +### Jobs
I don't see the change here

2024-09-26 21:43 UTC, TrevCraw commented on docs/LSP4IJ-Continuous-Integration.md
> +There are 4 jobs in the build. The first job, **PR details**, outputs a list of PRs in the LSP4IJ repository and displays warnings for any PRs that are either drafts or have merge conflicts.
```suggestion
There are four jobs in the build. The first job, **PR details**, outputs a list of PRs in the LSP4IJ repository and displays warnings for any PRs that are either drafts or have merge conflicts.
```

2024-09-26 21:43 UTC, TrevCraw commented on docs/LSP4IJ-Continuous-Integration.md
> +The next job **Run Lsp4ij Main** is the build which runs against the LSP4IJ main branch by checking out the LSP4IJ main branch. The job **Run PR** runs by checking out the merge commit SHAs of each P
```suggestion
The next job, **Run Lsp4ij Main**, is the build which runs against the LSP4IJ main branch by checking out the LSP4IJ main branch. The job **Run PR** runs by checking out the merge commit SHAs of each PR listed in the job **PR details**. The LSP4IJ PR number against which the job is run is displayed in the bracket, followed by the merge commit SHA. After the above three jobs are completed, the **Run Slack Notification** job runs and the Build results are sent as slack notification.
```

2024-09-26 21:43 UTC, TrevCraw commented on docs/LSP4IJ-Continuous-Integration.md
> +In the Annotations section, we get the details of the failed tests and also warnings of PRs with merge conflict.
```suggestion
The Annotations section contains errors that show the details of the failed builds and also warnings that show PRs with merge conflicts.
```

2024-09-26 21:43 UTC, TrevCraw commented on docs/LSP4IJ-Continuous-Integration.md
> +LSP4IJ nightly builds can be downloaded from the [JetBrains Marketplace](https://plugins.jetbrains.com/plugin/23257-lsp4ij/versions/nightly)
```suggestion
LSP4IJ nightly builds can be downloaded from the [JetBrains Marketplace](https://plugins.jetbrains.com/plugin/23257-lsp4ij/versions/nightly).
```

2024-09-26 21:43 UTC, TrevCraw commented on docs/user-guide.md
> +If you prefer to use an older version of LSP4IJ (e.g., the specific version that was tested with the Liberty Tools release you are using), you can manually downgrade it by installing the desired vers
```suggestion
If you prefer to use an older version of LSP4IJ (e.g., the specific version that was tested with the Liberty Tools release you are using), you can manually downgrade it by installing the desired version as a dependency from the [JetBrains marketplace](https://plugins.jetbrains.com/plugin/23257-lsp4ij/versions).
```

2024-09-27 07:04 UTC, anusreelakshmi934 commented on docs/LSP4IJ-Integration.md
> +### Jobs
Ok Trevor I initally thought the space between those outputs and inputs section. I have modified this section

2024-09-27 14:55 UTC, TrevCraw commented on docs/LSP4IJ-Integration.md
> +### Jobs
looks good now, thank you

2024-09-27 15:07 UTC, TrevCraw approved these changes

2024-09-27 15:57 UTC, mrglavas approved these changes
Reviewed with the team yesterday. Looks good.

2024-09-27 16:07 UTC, merged

2024-09-27 16:10 UTC, turkeylurkey approved these changes