Workaround Fix for Server.env Diagnostic and Popup Not Appearing Issue
OpenLiberty/liberty-tools-intellij pull request #992
Opened 2024-09-26 10:05 UTC by vaisakhkannan

As a workaround for this issue #945, the team has agreed to try `closing and reopening server.env ` after inserting the invalid value 'NONE'. 
We need to ensure the underlying issue is resolved in the future, and the workaround added in the PR should be removed at that time.

NOTE: I observed that there is no issue in the `server.env` files for version `0.3.0` (for all builds), but I found that the 'diagnostic not appearing' error leads to the 'hover not present' error in the server.env files for versions `0.4.0` and `0.5.0` (for all builds). Aparna also confirmed that the same issue is present in version 0.6.0 as well

2024-09-26 10:09 UTC, vaisakhkannan commented
For Reference: https://github.com/vaisakhkannan/liberty-tools-intellij/actions/runs/11045391029
https://github.com/vaisakhkannan/liberty-tools-intellij/actions/runs/11034622933

There are no builds failing due to the mentioned issue, so this workaround is acceptable for now to achieve green builds.

2024-10-03 04:48 UTC, aparnamichael commented on src/test/java/io/openliberty/tools/intellij/it/SingleModLibertyLSTestCommon.java
> +            // Close and reopen the server.env file as a workaround for the issue: https://github.com/OpenLiberty/liberty-tools-intellij/issues/945. Remove the two lines below once the root cause of
Please add "//TODO:" here

2024-10-03 13:30 UTC, vaisakhkannan commented on src/test/java/io/openliberty/tools/intellij/it/SingleModLibertyLSTestCommon.java
> +            // Close and reopen the server.env file as a workaround for the issue: https://github.com/OpenLiberty/liberty-tools-intellij/issues/945. Remove the two lines below once the root cause of
@aparnamichael , I added "TODO" .

2024-10-04 04:59 UTC, aparnamichael submitted a review, later dismissed
Looks good!!

2024-10-12 00:14 UTC, TrevCraw requested changes

2024-10-12 00:14 UTC, TrevCraw commented on src/test/java/io/openliberty/tools/intellij/it/SingleModLibertyLSTestCommon.java
> +            //TODO: Close and reopen the server.env file as a workaround for the issue: https://github.com/OpenLiberty/liberty-tools-intellij/issues/945. Remove the two lines below once the root caus
```suggestion
            //Close and reopen the server.env file as a workaround for the issue: https://github.com/OpenLiberty/liberty-tools-intellij/issues/945. 
            //TODO: Remove the two lines below once the root cause of issue 945 is fixed.
```

2024-10-14 12:58 UTC, aparnamichael approved these changes

2024-10-25 19:52 UTC, TrevCraw commented
Since we are getting close to a fix for https://github.com/redhat-developer/lsp4ij/issues/577, we may not need this workaround.

2024-11-12 19:40 UTC, TrevCraw commented
No longer need this workaround, since we have these two fixes:
- https://github.com/OpenLiberty/liberty-tools-intellij/pull/1051
- https://github.com/redhat-developer/lsp4ij/pull/587

2024-11-12 19:40 UTC, closed without merging